version: 2
updates:
  - package-ecosystem: gomod
    directory: "/backend"
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/smart-contract"
    schedule:
      interval: daily